# executable files for this directory
OBJECTS = book-store.exe

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include MS_makefile_template

main.obj sales-handling.obj: Sales_item.h
